import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '.././globals.css';
import MainHeader from '@/components/shared/main-header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container mx-auto'>
          <div className='min-h-screen bg-background px-2'>
            <MainHeader />
            <main className='container mx-auto mt-10'>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
